title: Technical Notes
description: Notes on cryptography and more. 

url: "https://FlippingACoin.github.io"
baseurl: ""

remote_theme: riggraz/no-style-please

markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: false

sass:
  style: compressed
